/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import Controller.UsuarioController;
import Interfaces.CrudUsuariosInterfaces;
import Model.PagoModel;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author EDER
 */
public class Agregar extends javax.swing.JPanel {

    private final UsuarioController USUARIO_CONTROLLER = new UsuarioController();

    boolean isEdition = false;
    PagoModel userEdition;

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
        initStyles();
    }

    public Agregar(PagoModel usuario) {
        initComponents();
        isEdition = true;
        userEdition = usuario;
        initStyles();
    }

    private void initStyles() {
        jTextFieldIdentificacion.putClientProperty("JTextField.placeholderText", "Ingrese la identificación del usuario");
        jTextFieldNombre.putClientProperty("JTextField.placeholderText", "Ingrese los nombres del usuario");
        jTextFieldApellidos.putClientProperty("JTextField.placeholderText", "Ingrese los apellidos del usuario");
        jTextFieldCorreo.putClientProperty("JTextField.placeholderText", "Ingrese el correo del usuario");
        jTextFieldTelefono.putClientProperty("JTextField.placeholderText", "Ingrese el teléfono del usuario");

        if (isEdition) {
            jLabel1.setText("Modificar Usuario");
            jButtonAgregarUsuario.setText("MODIFICAR");

            if (userEdition != null) {
                jTextFieldIdentificacion.setText(String.valueOf(userEdition.getIdentificacion()));
                jTextFieldNombre.setText(userEdition.getNombre_usuario());
                jTextFieldApellidos.setText(userEdition.getApellido_usuario());
                jTextFieldCorreo.setText(userEdition.getCorreo_usuario());
                jTextFieldTelefono.setText(String.valueOf(userEdition.getTelefono()));
                jComboBoxPlan.setSelectedItem(String.valueOf(userEdition.getPlan()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jButtonAgregarUsuario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPlan = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar nuevo Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Identificación");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        jTextFieldIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdentificacionKeyTyped(evt);
            }
        });
        add(jTextFieldIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 320, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombres");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 320, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Apellidos");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyTyped(evt);
            }
        });
        add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 320, 30));

        jSeparator1.setForeground(new java.awt.Color(45, 77, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 20, 370));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Correo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jTextFieldCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCorreoKeyTyped(evt);
            }
        });
        add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 320, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Teléfono");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyTyped(evt);
            }
        });
        add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 320, 30));

        jButtonAgregarUsuario.setBackground(new java.awt.Color(45, 77, 102));
        jButtonAgregarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAgregarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarUsuario.setText("AGREGAR");
        jButtonAgregarUsuario.setBorder(null);
        jButtonAgregarUsuario.setBorderPainted(false);
        jButtonAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarUsuarioActionPerformed(evt);
            }
        });
        add(jButtonAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 320, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Plan");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        jComboBoxPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 día", "15 días", "30 días" }));
        add(jComboBoxPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 320, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarUsuarioActionPerformed
        try {
            int id = Integer.parseInt(jTextFieldIdentificacion.getText());
            String nu = jTextFieldNombre.getText();
            String au = jTextFieldApellidos.getText();
            String cu = jTextFieldCorreo.getText();
            int tel = Integer.parseInt(jTextFieldTelefono.getText());
            String pl = (String) jComboBoxPlan.getSelectedItem();


            if (USUARIO_CONTROLLER.validarFormulario(id, nu, au, cu, tel, pl)) {
                if (!isEdition && USUARIO_CONTROLLER.existeUsuario(id)) {
                    JOptionPane.showMessageDialog(this, "EL USUARIO " + nu + " " + au + " YA EXISTE");
                } else {
                    PagoModel pm = isEdition ? userEdition : new PagoModel();
                    pm.setIdentificacion(id);
                    pm.setNombre_usuario(nu);
                    pm.setApellido_usuario(au);
                    pm.setCorreo_usuario(cu);
                    pm.setTelefono(tel);
                    pm.setPlan(pl);
                    if (!isEdition) {
                        pm.setPago_usuario(false);
                    } else {
                        pm.setPago_usuario(pm.isPago_usuario());
                    }

                    try {
                        CrudUsuariosInterfaces cui = new UsuarioController();
                        if (!isEdition) {
                            cui.agregar(pm);
                        } else {
                            cui.modificar(pm);
                        }

                        String successMsg = isEdition ? "MODIFICADO" : "REGISTRADO";
                        JOptionPane.showMessageDialog(this, "USUARIO " + successMsg);

                        if (!isEdition) {
                            jTextFieldIdentificacion.setText("");
                            jTextFieldNombre.setText("");
                            jTextFieldApellidos.setText("");
                            jTextFieldCorreo.setText("");
                            jTextFieldTelefono.setText("");
                            jComboBoxPlan.setSelectedItem("");
                        }
                    } catch (Exception e) {
                        String errorMsg = isEdition ? "MODIFICAR" : "REGISTRAR";
                        JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR AL " + errorMsg + "EL USUARIO \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "DEBE LLENAR TODOS LOS CAMPOS \n", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "LOS CAMPOS ESTÁN VACIOS");
        }
    }//GEN-LAST:event_jButtonAgregarUsuarioActionPerformed

    private void jTextFieldIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdentificacionKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;

        if (!numero) {
            evt.consume();
        }

        if (jTextFieldIdentificacion.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldIdentificacionKeyTyped

    private void jTextFieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyTyped
        int key = evt.getKeyChar();
        boolean numero = key >= 48 && key <= 57;

        if (!numero) {
            evt.consume();
        }

        if (jTextFieldTelefono.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyTyped
        if (!(Character.isLetter(evt.getKeyChar())) && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldApellidosKeyTyped

    private void jTextFieldCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCorreoKeyTyped
        char c = evt.getKeyChar(); // Permitir solo letras, números, '@', '.', '-', y '_' 
        if (!Character.isLetterOrDigit(c) && c != '@' && c != '.' && c != '-' && c != '_') {
            evt.consume(); // Si el carácter no es válido, se consume el evento 
        }
    }//GEN-LAST:event_jTextFieldCorreoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarUsuario;
    private javax.swing.JComboBox<String> jComboBoxPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldIdentificacion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
